### PR TITLE
Add FindPIO.cmake and FindPnetCDF.cmake

### PR DESCRIPTION
**Pull request by markjolah**
This PR adds FindPIO.cmake and FindPnetCDF.cmake.  These are required dependencies for mpasjedi.  Notes:
* FindPnetCDF.cmake uses the `pnetcdf-config` executable to glean the appropriate libraries, flags, and directories.  See documentation for details of how this can be located/specified.
* FindPIO.cmake can detect and export both shared and static components, allowing the user to request one type explicitly with a find_package() `COMPONENT`, and the appropriately named target.  See the documentation for details.

These will be copied into the MPAS-Model repo so that it can build with CMake without a dependency on this repo since the model is somewhat out of our ownership, asking to add jedi-cmake as a required dependency would be too much I think.  But I want to make sure we had a definitive copy of these under the JCSDA control here, so we can address any future issues more simply.

As the only current consumers of these are MPAS-Model and mpas-jedi, testing opportunities are limited to building the new branches of the mpas-bundle `feature/cmake-update`, with a matching PR to follow soon when I fix remaining testing bugs.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
How does one test this works?

Also, PIO already has a cmake build. Would it be possible to make a PR upstream.  I know the developers there are very responsive.

**Review by svahl991 — APPROVED** [review]
Looks good to me. Thanks for writing these!

**Comment by aerorahul** [comment]
@markjolah 

I actually have one suggestion, if possible. 
I will use PIO as an example.
Is it possible to make the change so say:

```
find_package(PIO COMPONENTS Fortran SHARED|STATIC)
```
instead of <Lang>_SHARED or <Lang>_STATIC?

The returned variables would then be needed to link with `PIO::PIO_Fortran`
i.e. `target_link_libraries(libName PIO::PIO_Fortran)`

And if `SHARED` is requested (default) `PIO_FORTRAN` is aliased to `PIO_FORTRAN_SHARED`
If `STATIC` is requested, `PIO_FORTRAN` is aliased to `PIO_FORTRAN_STATIC`.

I don't see a use case when both `SHARED` and `STATIC` libraries will be linked with in the same application.
This makes the use case general.

**Comment by aerorahul** [comment]
@markjolah 
The UFS will also be copying these into the UFS repository as well since it uses these libraries.
Thanks for this work.

**Comment by markjolah** [comment]
@aerorahul 
1. The problem with making the target alias depend on the requested components rather than the found components is that if different packages in a single bundle requested different components that the main target link would change where it points and the system would break. 
2. The CMake build from PIO does not provide a CMake Config file, so we are forced to go the Find Module route.  Also they don't provide pkg-config or anything else to help, so we are on our own.
3. Based on the way the PIO build system works it is impossible to have Fortran_STATIC and not C_STATIC, and vise-versa.  Either both libraries are present and static or both are present and shared, or all four combinations are present.  This way we only need STATIC and SHARED compnents.

I should note these are still not working for compiling static binaries, and I need to figure out how to manage that.  The PIO STATIC targets still require the NetCDF static libraries to link against.  For building shared libraries and executables, it all is working and it appears to also work if you have static libaries to link against assuming they were compiled with `-fPIC`, as is the case with the JEDI-stack build.

**Comment by markjolah** [comment]
Ok reading the PIO CMake a little more carefully there is one clarification, it is possible to not have Fortran at all (but we always need the Fortran component for JEDI), but if you have C_STATIC and Fortran, then you must have Fortran_STATIC.  And if you have C_SHARED and Fortran, then you must have Fortran_SHARED.

**Comment by markjolah** [comment]
@aerorahul Sorry I think I totally missunderstood you and I'm arguing against my own decisions.  I like your suggestion and will implement it.

**Comment by aerorahul** [comment]
> @aerorahul Sorry I think I totally missunderstood you and I'm arguing against my own decisions. I like your suggestion and will implement it.

@markjolah No worries.
You can see my updates [here](https://github.com/JCSDA/jedi-cmake/blob/feature/find_pio2_pnetcdf/cmake/Modules/FindPIO.cmake)

**Comment by markjolah** [comment]
Okay.  I simplified the components list as suggested, but I still can't make the target aliases the way you'd like because of the issue of multiple packages in a bundle (or dependencies from an <pkg>-imports.cmake) asking for differing components.  It will produce an error when the second invocation tries to create/modify an alias that already exists.  I think this is the best we can do.  For static users they will want to use the `PIO::Fortran_<LANG>_STATIC` targets explicitly and request `find_package(PIO REQUIRED COMPONENTS STATIC)`.  Normally this decision is made based on the CMake [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) variable.

I expect there are still quite a few bugs to be found with these when building static libs, we're mainly just supporting building shared at the moment, because it's much simpler.

**Review by mmiesch — APPROVED** [review]

**Pull request merged**
